name: GitHub Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # Runs every day at midnight UTC
  push: { branches: ["main"] }

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          plugin_contributions: yes
